before:
  hooks:
    - go mod download
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
archives:
- format_overrides:
    - goos: windows
      format: zip
release:
  github:
  prerelease: auto
dockers:
  -
    image_templates:
    - "docker.pkg.github.com/golang-templates/seed/{{.projectName}}:latest"
    - "docker.pkg.github.com/golang-templates/seed/{{.projectName}}:{{`{{.Major}}`}}"
    - "docker.pkg.github.com/golang-templates/seed/{{.projectName}}:{{`{{.Major}}`}}.{{`{{.Minor}}`}}"
    - "docker.pkg.github.com/golang-templates/seed/{{.projectName}}:{{`{{.Major}}`}}.{{`{{.Minor}}`}}.{{`{{.Patch}}`}}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{`{{.Date}}`}}"
    - "--label=org.opencontainers.image.name={{.projectName}}"
    - "--label=org.opencontainers.image.revision={{`{{.FullCommit}}`}}"
    - "--label=org.opencontainers.image.version={{`{{.Version}}`}}"
    - "--label=org.opencontainers.image.source={{`{{.GitURL}}`}}"
