version: v1
mode: goTemplate

variables:
  - name: projectName
    description: Name of your repository
  - name: applicationVersion
    default: 0.0.1
  - name: applicationName
    secret: true
  - name: goVersion
    default: 1.17
    description: Version of Go
  - name: organizerion
    description: Name of your Github organization
    
